version: "3"
services:

  event-bus:
    image: redis:7.2-bookworm
    command: redis-server --requirepass redis --maxmemory 512mb

  gateway:
    image: nginx:1.25-bookworm
    volumes:
      - ./gateway_nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8000:80"
    depends_on:
      - order-service
      - stock-service
      - payment-service
      - event-bus

  order-service:
    build: ./order
    image: order:latest
    environment:
      - GATEWAY_URL=http://gateway:80
      - REDIS_HOST=order-db
      - EVENT_REDIS_HOST=event-bus
    command: gunicorn -b 0.0.0.0:5000 -w 2 --timeout 30 --log-level=info app:app
    env_file:
      - env/order_redis.env
    depends_on:
      - order-db
      - event-bus

  stock-service:
    build: ./stock
    image: stock:latest
    environment:
      - REDIS_HOST=stock-db
      - EVENT_REDIS_HOST=event-bus
    command: gunicorn -b 0.0.0.0:5000 -w 2 --timeout 30 --log-level=info app:app
    env_file:
      - env/stock_redis.env
    depends_on:
      - stock-db
      - event-bus

  payment-service:
    build: ./payment
    image: user:latest
    environment:
      - REDIS_HOST=payment-db
      - EVENT_REDIS_HOST=event-bus
    command: gunicorn -b 0.0.0.0:5000 -w 2 --timeout 30 --log-level=info app:app
    env_file:
      - env/payment_redis.env
    depends_on:
      - payment-db
      - event-bus

  order-db:
    image: redis:7.2-bookworm
    container_name: order-db
    command: redis-server --requirepass redis --maxmemory 512mb --masterauth redis
    networks:
      - app-net

  order-db-replica:
    image: redis:7.2-bookworm
    container_name: order-db-replica
    command: redis-server --requirepass redis --maxmemory 512mb --slaveof order-db 6379 --masterauth redis
    networks:
      - app-net

  redis-sentinel-order:
    image: redis:7.2-bookworm
    command: redis-server /usr/local/etc/redis/sentinel-order.conf --sentinel
    volumes:
      - ./sentinel_conf:/usr/local/etc/redis
    environment:
      - REDIS_PASSWORD=redis
    depends_on:
      - order-db
    networks:
      - app-net

  stock-db:
    image: redis:7.2-bookworm
    container_name: stock-db
    command: redis-server --requirepass redis --maxmemory 512mb --masterauth redis
    networks:
      - app-net

  stock-db-replica:
    image: redis:7.2-bookworm
    container_name: stock-db-replica
    command: redis-server --requirepass redis --maxmemory 512mb --slaveof stock-db 6379 --masterauth redis
    networks:
      - app-net

  redis-sentinel-stock:
    image: redis:7.2-bookworm
    command: redis-server /usr/local/etc/redis/sentinel-stock.conf --sentinel
    volumes:
      - ./sentinel_conf:/usr/local/etc/redis
    environment:
      - REDIS_PASSWORD=redis
    depends_on:
      - stock-db
    networks:
      - app-net

  payment-db:
    image: redis:7.2-bookworm
    command: redis-server --requirepass redis --maxmemory 512mb --masterauth redis

  payment-db-replica:
    image: redis:7.2-bookworm
    command: redis-server --requirepass redis --maxmemory 512mb --slaveof payment-db 6379 --masterauth redis

  redis-sentinel-payment:
    image: redis:7.2-bookworm
    command: redis-server /etc/redis/sentinel-payment.conf --sentinel
    volumes:
      - ./sentinel-configs/sentinel-payment.conf:/etc/redis/sentinel-payment.conf
    environment:
      - REDIS_PASSWORD=redis
    depends_on:
      - payment-db

networks:
  app-net:
    driver: bridge