version: "3"
services:

  event-bus:
    image: redis:7.2-bookworm
    command: redis-server --requirepass redis --maxmemory 512mb

  gateway:
    image: nginx:1.25-bookworm
    volumes:
      - ./gateway_nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8000:80"
    depends_on:
      - order-service
      - stock-service
      - payment-service
      - event-bus

  order-service:
    build: ./order
    image: order:latest
    environment:
      - GATEWAY_URL=http://gateway:80
      - REDIS_HOST=order-db
      - SENTINEL_HOST=redis-sentinel-order
      - EVENT_REDIS_HOST=event-bus
    command: gunicorn -b 0.0.0.0:5000 -w 2 --timeout 30 --log-level=info app:app
    env_file:
      - env/order_redis.env
    depends_on:
      - order-db
      - event-bus
    networks:
      - default
      - order-net

  stock-service:
    build: ./stock
    image: stock:latest
    environment:
      - REDIS_HOST=stock-db
      - SENTINEL_HOST=redis-sentinel-stock
      - EVENT_REDIS_HOST=event-bus
    command: gunicorn -b 0.0.0.0:5000 -w 2 --timeout 30 --log-level=info app:app
    env_file:
      - env/stock_redis.env
    depends_on:
      - stock-db
      - event-bus
    networks:
      - default
      - stock-net

  payment-service:
    build: ./payment
    image: user:latest
    environment:
      - REDIS_HOST=payment-db
      - SENTINEL_HOST=redis-sentinel-payment
      - EVENT_REDIS_HOST=event-bus
    command: gunicorn -b 0.0.0.0:5000 -w 2 --timeout 30 --log-level=info app:app
    env_file:
      - env/payment_redis.env
    depends_on:
      - payment-db
      - event-bus
    networks:
      - default
      - payment-net

  order-db:
    image: redis:7.2-bookworm
    container_name: order-db
    command: redis-server --requirepass redis --maxmemory 512mb --masterauth redis
    networks:
      - order-net

  order-db-replica:
    image: redis:7.2-bookworm
    container_name: order-db-replica
    command: redis-server --requirepass redis --maxmemory 512mb --slaveof order-db 6379 --masterauth redis
    networks:
      - order-net

  redis-sentinel-order:
    image: redis:7.2-bookworm
    container_name: redis-sentinel-order
    build:
      context: .
      dockerfile: order_dockserfile
    command: [ "bash", "/usr/local/bin/create_order_conf.sh" ]
    environment:
      - REDIS_PASSWORD=redis
      - REDIS_MASTER_NAME=mymaster
    depends_on:
      - order-db
    networks:
      - order-net

  stock-db:
    image: redis:7.2-bookworm
    container_name: stock-db
    command: redis-server --requirepass redis --maxmemory 512mb --masterauth redis
    networks:
      - stock-net

  stock-db-replica:
    image: redis:7.2-bookworm
    container_name: stock-db-replica
    command: redis-server --requirepass redis --maxmemory 512mb --slaveof stock-db 6379 --masterauth redis
    networks:
      - stock-net

  redis-sentinel-stock:
    image: redis:7.2-bookworm
    container_name: redis-sentinel-stock
    build:
      context: .
      dockerfile: stock_dockserfile
    command: [ "bash", "/usr/local/bin/create_stock_conf.sh" ]
    environment:
      - REDIS_PASSWORD=redis
      - REDIS_MASTER_NAME=mymaster
    depends_on:
      - stock-db
    networks:
      - stock-net

  payment-db:
    image: redis:7.2-bookworm
    container_name: payment-db
    command: redis-server --requirepass redis --maxmemory 512mb --masterauth redis
    networks:
      - payment-net

  payment-db-replica:
    image: redis:7.2-bookworm
    container_name: payment-db-replica
    command: redis-server --requirepass redis --maxmemory 512mb --slaveof payment-db 6379 --masterauth redis
    networks:
      - payment-net

  redis-sentinel-payment:
    image: redis:7.2-bookworm
    container_name: redis-sentinel-payment
    build:
      context: .
      dockerfile: payment_dockserfile
    command: [ "bash", "/usr/local/bin/create_payment_conf.sh" ]
    environment:
      - REDIS_PASSWORD=redis
      - REDIS_MASTER_NAME=mymaster
    depends_on:
      - payment-db
    networks:
      - payment-net

networks:
  order-net:
    driver: bridge
  stock-net:
    driver: bridge
  payment-net:
    driver: bridge
