listeners:
  client:
    protocol: PLAINTEXT
  controller:
    protocol: PLAINTEXT
  interbroker:
    protocol: PLAINTEXT
provisioning:
  enabled: true
  topics:
    - name: order
      partitions: 1
      replicationFactor: 1
      config:
        max.message.bytes: 64000
        flush.messages: 1
    - name: stock
      partitions: 1
      replicationFactor: 1
      config:
        max.message.bytes: 64000
        flush.messages: 1
    - name: payment
      partitions: 1
      replicationFactor: 1
      config:
        max.message.bytes: 64000
        flush.messages: 1