auth:
  password: redis
master:
  persistence:
    size: 1Gi
  resources:
    requests:
      memory: 1Gi
      cpu: 500m
replica:
  replicaCount: 1
  persistence:
    size: 1Gi
  resources:
    requests:
      memory: 1Gi
      cpu: 200m