auth:
  password: redis
master:
  persistence:
    size: 0.5Gi
  resources:
    requests:
      memory: 0.5Gi
      cpu: 500m
replica:
  replicaCount: 1
  persistence:
    size: 0.5Gi
  resources:
    requests:
      memory: 0.5Gi
      cpu: 200m